// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBW-4pGMBR6lvu0E1HNhKoa5-fEcPBs_6A',
    appId: '1:3580155515:web:f53a7b1b3320b9d8cf0c5e',
    messagingSenderId: '35801355515',
    projectId: 'carwash-3a5f9',
    authDomain: 'carwash-3a5f9.firebaseapp.com',
    storageBucket: 'carwash-3a5f9.appspot.com',
  );
    static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBW-4pGMBR6lvu0E1HNhKoa5-fEcPBs_6A',
    appId: '1:3580155515:android:f53a7b1b3320b9d8cf0c5e', 
    messagingSenderId: '35801355515	',
    projectId: 'carwash-3a5f9',
    storageBucket: 'carwash-3a5f9.appspot.com',
  );

  // static const FirebaseOptions android = FirebaseOptions(
  //   apiKey: 'AIzaSyDN91DnOsQYhItvpYUx1pJAnvmbGk2ntlE',
  //   appId: '1:65298134803:android:bfb9da3d1ed2e882174ce6', //
  //   messagingSenderId: '65298134803',
  //   projectId: 'firestore-uber',
  //   storageBucket: 'firestore-uber.appspot.com',
  // );
}
